### ISSUE TITLE
Are there plans to add write/update functionality ("Update edge config items in batch")

### ISSUE THREAD

**Issue by jzxhuang** [vercel/edge-config#69]
I'm wondering if there are plans to add write/update functionality!

Atm when working w/ Edge Config, I write a light wrapper that re-exports everything in the SDK and additionally implements a `patch` function calls `https://api.vercel.com/v1/edge-config/${edgeConfigId}/items${teamId ? "?teamId=${teamId}" : ''` with Vercel API token

I had to dig around a little though — the API docs confused me at first, I incorrectly used "[Update Edge Config](https://vercel.com/docs/rest-api#endpoints/edge-config/updates-an-edge-config)"  endpoint first instead of the "[Update Edge Config items in batch](https://vercel.com/docs/rest-api#endpoints/edge-config/update-edge-config-items-in-batch)" 🙈 

Obviously it ended up being simple to implement, but would be even nicer if it was part of the SDK with type defs and all that good stuff 😄

**Comment by dferber90** [comment]
Thanks for flagging this! We made a deliberate decision not to support updating functionality from the SDK as we wanted to avoid people thinking that this is suitable for large write volume or that you can read your own write.

We basically wanted to get ahead of people trying to use this for API Rate Limiting, Session Storage, Counters and so on. 

That said, we should probably at least mention how people can actually write values using the UI or API in the README <picture data-single-emoji=":blob_smile:" title=":blob_smile:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..2yi5QO7-oXo7z4xN.TP3deKYXCw6FwTnN8aJM2cbY1h8aKNAa5PNVEniTqqkWncfaMa4K9EgGNmQfqvjoQ3QDgoqOlOcsQjf7FTAptjqwoh3TJnGNMTIrIRyoW9cKZ2mZt_SNL9jM_50.Muxv3gFIHSKCxTYOb1RIwg" alt=":blob_smile:" align="absmiddle"></picture> 

_Apologies for the late reply, I just realized my notifications were configured incorrectly._

**Comment by dferber90** [comment]
I've opened https://github.com/vercel/edge-config/pull/82 which will mention it in the README itself, thanks for your input here on making this easier to discover!
